# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_font_convert_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_font_convert_form(object):
    def setupUi(self, hcmgis_font_convert_form):
        hcmgis_font_convert_form.setObjectName("hcmgis_font_convert_form")
        hcmgis_font_convert_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_font_convert_form.setEnabled(True)
        hcmgis_font_convert_form.resize(413, 385)
        hcmgis_font_convert_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_font_convert_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LblInput = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblInput.setObjectName("LblInput")
        self.verticalLayout.addWidget(self.LblInput)
        self.CboInput = QgsMapLayerComboBox(hcmgis_font_convert_form)
        self.CboInput.setObjectName("CboInput")
        self.verticalLayout.addWidget(self.CboInput)
        self.LblOutput_2 = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblOutput_2.setObjectName("LblOutput_2")
        self.verticalLayout.addWidget(self.LblOutput_2)
        self.ListFields = QtWidgets.QListWidget(hcmgis_font_convert_form)
        self.ListFields.setAlternatingRowColors(True)
        self.ListFields.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ListFields.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ListFields.setObjectName("ListFields")
        self.verticalLayout.addWidget(self.ListFields)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.LblSourceFont = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblSourceFont.setObjectName("LblSourceFont")
        self.gridLayout.addWidget(self.LblSourceFont, 0, 0, 1, 1)
        self.CboSourceFont = QtWidgets.QComboBox(hcmgis_font_convert_form)
        self.CboSourceFont.setObjectName("CboSourceFont")
        self.CboSourceFont.addItem("")
        self.CboSourceFont.setItemText(0, "")
        self.CboSourceFont.addItem("")
        self.CboSourceFont.addItem("")
        self.CboSourceFont.addItem("")
        self.gridLayout.addWidget(self.CboSourceFont, 1, 0, 1, 1)
        self.CboDestFont = QtWidgets.QComboBox(hcmgis_font_convert_form)
        self.CboDestFont.setObjectName("CboDestFont")
        self.CboDestFont.addItem("")
        self.CboDestFont.setItemText(0, "")
        self.CboDestFont.addItem("")
        self.CboDestFont.addItem("")
        self.CboDestFont.addItem("")
        self.CboDestFont.addItem("")
        self.gridLayout.addWidget(self.CboDestFont, 1, 1, 1, 2)
        self.CboOption = QtWidgets.QComboBox(hcmgis_font_convert_form)
        self.CboOption.setObjectName("CboOption")
        self.CboOption.addItem("")
        self.CboOption.setItemText(0, "")
        self.CboOption.addItem("")
        self.CboOption.addItem("")
        self.CboOption.addItem("")
        self.CboOption.addItem("")
        self.gridLayout.addWidget(self.CboOption, 3, 0, 1, 1)
        self.ChkSelectedFeaturesOnly = QtWidgets.QCheckBox(hcmgis_font_convert_form)
        self.ChkSelectedFeaturesOnly.setObjectName("ChkSelectedFeaturesOnly")
        self.gridLayout.addWidget(self.ChkSelectedFeaturesOnly, 3, 1, 1, 2)
        self.LinOutput = QtWidgets.QLineEdit(hcmgis_font_convert_form)
        self.LinOutput.setObjectName("LinOutput")
        self.gridLayout.addWidget(self.LinOutput, 5, 0, 1, 2)
        self.BtnBrowseOutput = QtWidgets.QPushButton(hcmgis_font_convert_form)
        self.BtnBrowseOutput.setObjectName("BtnBrowseOutput")
        self.gridLayout.addWidget(self.BtnBrowseOutput, 5, 2, 1, 1)
        self.LblDestFont = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblDestFont.setObjectName("LblDestFont")
        self.gridLayout.addWidget(self.LblDestFont, 0, 1, 1, 2)
        self.LblOption = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblOption.setObjectName("LblOption")
        self.gridLayout.addWidget(self.LblOption, 2, 0, 1, 3)
        self.LblOutput = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblOutput.setObjectName("LblOutput")
        self.gridLayout.addWidget(self.LblOutput, 4, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(hcmgis_font_convert_form)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_font_convert_form)
        self.BtnApplyClose.accepted.connect(hcmgis_font_convert_form.accept)
        self.BtnApplyClose.rejected.connect(hcmgis_font_convert_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_font_convert_form)

    def retranslateUi(self, hcmgis_font_convert_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_font_convert_form.setWindowTitle(_translate("hcmgis_font_convert_form", "Vietnamese Font Converter"))
        self.LblInput.setText(_translate("hcmgis_font_convert_form", "Input Layer"))
        self.LblOutput_2.setText(_translate("hcmgis_font_convert_form", "Fields"))
        self.LblSourceFont.setText(_translate("hcmgis_font_convert_form", "Source Charset"))
        self.CboSourceFont.setItemText(1, _translate("hcmgis_font_convert_form", "TCVN3"))
        self.CboSourceFont.setItemText(2, _translate("hcmgis_font_convert_form", "Unicode"))
        self.CboSourceFont.setItemText(3, _translate("hcmgis_font_convert_form", "VNI-Windows"))
        self.CboDestFont.setItemText(1, _translate("hcmgis_font_convert_form", "Unicode"))
        self.CboDestFont.setItemText(2, _translate("hcmgis_font_convert_form", "TCVN3"))
        self.CboDestFont.setItemText(3, _translate("hcmgis_font_convert_form", "VNI-Windows"))
        self.CboDestFont.setItemText(4, _translate("hcmgis_font_convert_form", "ANSI (Khong dau)"))
        self.CboOption.setItemText(1, _translate("hcmgis_font_convert_form", "UPPER CASE (IN HOA)"))
        self.CboOption.setItemText(2, _translate("hcmgis_font_convert_form", "lower case (in thường)"))
        self.CboOption.setItemText(3, _translate("hcmgis_font_convert_form", "Capitalize (Hoa đầu câu)"))
        self.CboOption.setItemText(4, _translate("hcmgis_font_convert_form", "Title (Hoa Mỗi từ)"))
        self.ChkSelectedFeaturesOnly.setText(_translate("hcmgis_font_convert_form", "Selected features only"))
        self.BtnBrowseOutput.setText(_translate("hcmgis_font_convert_form", "..."))
        self.LblDestFont.setText(_translate("hcmgis_font_convert_form", "Target Charset"))
        self.LblOption.setText(_translate("hcmgis_font_convert_form", "Options"))
        self.LblOutput.setText(_translate("hcmgis_font_convert_form", "Output Shapefile"))

from qgsmaplayercombobox import QgsMapLayerComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_font_convert_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_font_convert_form()
    ui.setupUi(hcmgis_font_convert_form)
    hcmgis_font_convert_form.show()
    sys.exit(app.exec_())

