# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_split_field_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_split_field_form(object):
    def setupUi(self, hcmgis_split_field_form):
        hcmgis_split_field_form.setObjectName("hcmgis_split_field_form")
        hcmgis_split_field_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_split_field_form.setEnabled(True)
        hcmgis_split_field_form.resize(341, 218)
        hcmgis_split_field_form.setMouseTracking(False)
        self.LblChar = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblChar.setGeometry(QtCore.QRect(10, 101, 321, 16))
        self.LblChar.setObjectName("LblChar")
        self.CboChar = QtWidgets.QComboBox(hcmgis_split_field_form)
        self.CboChar.setGeometry(QtCore.QRect(10, 121, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CboChar.setFont(font)
        self.CboChar.setEditable(True)
        self.CboChar.setObjectName("CboChar")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.BtnOKCancel = QtWidgets.QDialogButtonBox(hcmgis_split_field_form)
        self.BtnOKCancel.setGeometry(QtCore.QRect(175, 180, 156, 31))
        self.BtnOKCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.BtnOKCancel.setObjectName("BtnOKCancel")
        self.LblInput = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblInput.setGeometry(QtCore.QRect(10, 7, 321, 16))
        self.LblInput.setObjectName("LblInput")
        self.CboInput = QgsMapLayerComboBox(hcmgis_split_field_form)
        self.CboInput.setGeometry(QtCore.QRect(10, 24, 321, 21))
        self.CboInput.setObjectName("CboInput")
        self.LblOutput_2 = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblOutput_2.setGeometry(QtCore.QRect(10, 54, 321, 16))
        self.LblOutput_2.setObjectName("LblOutput_2")
        self.CboField = QgsFieldComboBox(hcmgis_split_field_form)
        self.CboField.setGeometry(QtCore.QRect(10, 70, 321, 21))
        self.CboField.setObjectName("CboField")
        self.ChkSelectedFeaturesOnly = QtWidgets.QCheckBox(hcmgis_split_field_form)
        self.ChkSelectedFeaturesOnly.setGeometry(QtCore.QRect(10, 157, 151, 17))
        self.ChkSelectedFeaturesOnly.setObjectName("ChkSelectedFeaturesOnly")

        self.retranslateUi(hcmgis_split_field_form)
        self.BtnOKCancel.accepted.connect(hcmgis_split_field_form.accept)
        self.BtnOKCancel.rejected.connect(hcmgis_split_field_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_split_field_form)

    def retranslateUi(self, hcmgis_split_field_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_split_field_form.setWindowTitle(_translate("hcmgis_split_field_form", "Split Fields"))
        self.LblChar.setText(_translate("hcmgis_split_field_form", "Split character"))
        self.CboChar.setItemText(0, _translate("hcmgis_split_field_form", "Space"))
        self.CboChar.setItemText(1, _translate("hcmgis_split_field_form", "Tab"))
        self.CboChar.setItemText(2, _translate("hcmgis_split_field_form", ","))
        self.CboChar.setItemText(3, _translate("hcmgis_split_field_form", "_"))
        self.CboChar.setItemText(4, _translate("hcmgis_split_field_form", "-"))
        self.CboChar.setItemText(5, _translate("hcmgis_split_field_form", "/"))
        self.CboChar.setItemText(6, _translate("hcmgis_split_field_form", "|"))
        self.CboChar.setItemText(7, _translate("hcmgis_split_field_form", "\\"))
        self.CboChar.setItemText(8, _translate("hcmgis_split_field_form", "."))
        self.CboChar.setItemText(9, _translate("hcmgis_split_field_form", ":"))
        self.CboChar.setItemText(10, _translate("hcmgis_split_field_form", ";"))
        self.CboChar.setItemText(11, _translate("hcmgis_split_field_form", "~"))
        self.CboChar.setItemText(12, _translate("hcmgis_split_field_form", "`"))
        self.CboChar.setItemText(13, _translate("hcmgis_split_field_form", "!"))
        self.CboChar.setItemText(14, _translate("hcmgis_split_field_form", "@"))
        self.CboChar.setItemText(15, _translate("hcmgis_split_field_form", "#"))
        self.CboChar.setItemText(16, _translate("hcmgis_split_field_form", "$"))
        self.CboChar.setItemText(17, _translate("hcmgis_split_field_form", "%"))
        self.CboChar.setItemText(18, _translate("hcmgis_split_field_form", "&"))
        self.CboChar.setItemText(19, _translate("hcmgis_split_field_form", "*"))
        self.CboChar.setItemText(20, _translate("hcmgis_split_field_form", "("))
        self.CboChar.setItemText(21, _translate("hcmgis_split_field_form", ")"))
        self.CboChar.setItemText(22, _translate("hcmgis_split_field_form", "{"))
        self.CboChar.setItemText(23, _translate("hcmgis_split_field_form", "}"))
        self.CboChar.setItemText(24, _translate("hcmgis_split_field_form", "["))
        self.CboChar.setItemText(25, _translate("hcmgis_split_field_form", "]"))
        self.CboChar.setItemText(26, _translate("hcmgis_split_field_form", "\'"))
        self.CboChar.setItemText(27, _translate("hcmgis_split_field_form", "\""))
        self.CboChar.setItemText(28, _translate("hcmgis_split_field_form", "<"))
        self.CboChar.setItemText(29, _translate("hcmgis_split_field_form", ">"))
        self.LblInput.setText(_translate("hcmgis_split_field_form", "Input Layer"))
        self.LblOutput_2.setText(_translate("hcmgis_split_field_form", "Split field"))
        self.ChkSelectedFeaturesOnly.setText(_translate("hcmgis_split_field_form", "Selected features only"))

from qgis.gui import QgsFieldComboBox, QgsMapLayerComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_split_field_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_split_field_form()
    ui.setupUi(hcmgis_split_field_form)
    hcmgis_split_field_form.show()
    sys.exit(app.exec_())

