# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_format_convert_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_format_convert_form(object):
    def setupUi(self, hcmgis_format_convert_form):
        hcmgis_format_convert_form.setObjectName("hcmgis_format_convert_form")
        hcmgis_format_convert_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_format_convert_form.setEnabled(True)
        hcmgis_format_convert_form.resize(572, 454)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        hcmgis_format_convert_form.setFont(font)
        hcmgis_format_convert_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_format_convert_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cboOutputFormat = QtWidgets.QComboBox(hcmgis_format_convert_form)
        self.cboOutputFormat.setObjectName("cboOutputFormat")
        self.cboOutputFormat.addItem("")
        self.cboOutputFormat.addItem("")
        self.cboOutputFormat.addItem("")
        self.cboOutputFormat.addItem("")
        self.cboOutputFormat.addItem("")
        self.cboOutputFormat.addItem("")
        self.cboOutputFormat.addItem("")
        self.gridLayout_2.addWidget(self.cboOutputFormat, 2, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(hcmgis_format_convert_form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(hcmgis_format_convert_form)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.cboInputFormat = QtWidgets.QComboBox(hcmgis_format_convert_form)
        self.cboInputFormat.setObjectName("cboInputFormat")
        self.cboInputFormat.addItem("")
        self.cboInputFormat.addItem("")
        self.cboInputFormat.addItem("")
        self.cboInputFormat.addItem("")
        self.cboInputFormat.addItem("")
        self.cboInputFormat.addItem("")
        self.cboInputFormat.addItem("")
        self.gridLayout_2.addWidget(self.cboInputFormat, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.label_2 = QtWidgets.QLabel(hcmgis_format_convert_form)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BtnInputFolder = QtWidgets.QPushButton(hcmgis_format_convert_form)
        self.BtnInputFolder.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.BtnInputFolder.setFont(font)
        self.BtnInputFolder.setObjectName("BtnInputFolder")
        self.gridLayout_3.addWidget(self.BtnInputFolder, 0, 1, 1, 1)
        self.LinInputFolder = QtWidgets.QLineEdit(hcmgis_format_convert_form)
        self.LinInputFolder.setEnabled(True)
        self.LinInputFolder.setMouseTracking(True)
        self.LinInputFolder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LinInputFolder.setAcceptDrops(False)
        self.LinInputFolder.setText("")
        self.LinInputFolder.setReadOnly(False)
        self.LinInputFolder.setObjectName("LinInputFolder")
        self.gridLayout_3.addWidget(self.LinInputFolder, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.lblFiles = QtWidgets.QLabel(hcmgis_format_convert_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblFiles.setFont(font)
        self.lblFiles.setText("")
        self.lblFiles.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lblFiles.setObjectName("lblFiles")
        self.verticalLayout.addWidget(self.lblFiles)
        self.lsFiles = QtWidgets.QListWidget(hcmgis_format_convert_form)
        self.lsFiles.setObjectName("lsFiles")
        self.verticalLayout.addWidget(self.lsFiles)
        self.lblStatus = QtWidgets.QLabel(hcmgis_format_convert_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblStatus.setFont(font)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.verticalLayout.addWidget(self.lblStatus)
        self.status = QtWidgets.QProgressBar(hcmgis_format_convert_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.label = QtWidgets.QLabel(hcmgis_format_convert_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtError = QtWidgets.QTextEdit(hcmgis_format_convert_form)
        self.txtError.setObjectName("txtError")
        self.verticalLayout.addWidget(self.txtError)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(hcmgis_format_convert_form)
        self.BtnApplyClose.setOrientation(QtCore.Qt.Horizontal)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setCenterButtons(False)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_format_convert_form)
        self.BtnApplyClose.accepted.connect(hcmgis_format_convert_form.accept)
        self.BtnApplyClose.rejected.connect(hcmgis_format_convert_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_format_convert_form)

    def retranslateUi(self, hcmgis_format_convert_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_format_convert_form.setWindowTitle(_translate("hcmgis_format_convert_form", "Vector Format Batch Convert"))
        self.cboOutputFormat.setItemText(0, _translate("hcmgis_format_convert_form", "GeoJSON"))
        self.cboOutputFormat.setItemText(1, _translate("hcmgis_format_convert_form", "Esri Shapefile"))
        self.cboOutputFormat.setItemText(2, _translate("hcmgis_format_convert_form", "DXF"))
        self.cboOutputFormat.setItemText(3, _translate("hcmgis_format_convert_form", "DGN"))
        self.cboOutputFormat.setItemText(4, _translate("hcmgis_format_convert_form", "GPKG"))
        self.cboOutputFormat.setItemText(5, _translate("hcmgis_format_convert_form", "GML"))
        self.cboOutputFormat.setItemText(6, _translate("hcmgis_format_convert_form", "KML"))
        self.label_7.setText(_translate("hcmgis_format_convert_form", "Output Format"))
        self.label_8.setText(_translate("hcmgis_format_convert_form", "Input Format"))
        self.cboInputFormat.setItemText(0, _translate("hcmgis_format_convert_form", "Esri Shapefile"))
        self.cboInputFormat.setItemText(1, _translate("hcmgis_format_convert_form", "DXF"))
        self.cboInputFormat.setItemText(2, _translate("hcmgis_format_convert_form", "DGN"))
        self.cboInputFormat.setItemText(3, _translate("hcmgis_format_convert_form", "GPKG"))
        self.cboInputFormat.setItemText(4, _translate("hcmgis_format_convert_form", "GeoJSON"))
        self.cboInputFormat.setItemText(5, _translate("hcmgis_format_convert_form", "GML"))
        self.cboInputFormat.setItemText(6, _translate("hcmgis_format_convert_form", "KML"))
        self.label_2.setText(_translate("hcmgis_format_convert_form", "Input Folder"))
        self.BtnInputFolder.setText(_translate("hcmgis_format_convert_form", "Browse..."))
        self.label.setText(_translate("hcmgis_format_convert_form", "Errors Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_format_convert_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_format_convert_form()
    ui.setupUi(hcmgis_format_convert_form)
    hcmgis_format_convert_form.show()
    sys.exit(app.exec_())

