# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_font_convert_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_font_convert_form(object):
    def setupUi(self, hcmgis_font_convert_form):
        hcmgis_font_convert_form.setObjectName("hcmgis_font_convert_form")
        hcmgis_font_convert_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_font_convert_form.setEnabled(True)
        hcmgis_font_convert_form.resize(351, 380)
        hcmgis_font_convert_form.setMouseTracking(False)
        self.LblSourceFont = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblSourceFont.setGeometry(QtCore.QRect(10, 190, 151, 16))
        self.LblSourceFont.setObjectName("LblSourceFont")
        self.LblDestFont = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblDestFont.setGeometry(QtCore.QRect(190, 190, 151, 16))
        self.LblDestFont.setObjectName("LblDestFont")
        self.CboSourceFont = QtWidgets.QComboBox(hcmgis_font_convert_form)
        self.CboSourceFont.setGeometry(QtCore.QRect(10, 207, 151, 21))
        self.CboSourceFont.setObjectName("CboSourceFont")
        self.CboSourceFont.addItem("")
        self.CboSourceFont.setItemText(0, "")
        self.CboSourceFont.addItem("")
        self.CboSourceFont.addItem("")
        self.CboSourceFont.addItem("")
        self.CboDestFont = QtWidgets.QComboBox(hcmgis_font_convert_form)
        self.CboDestFont.setGeometry(QtCore.QRect(190, 206, 151, 21))
        self.CboDestFont.setObjectName("CboDestFont")
        self.CboDestFont.addItem("")
        self.CboDestFont.setItemText(0, "")
        self.CboDestFont.addItem("")
        self.CboDestFont.addItem("")
        self.CboDestFont.addItem("")
        self.CboDestFont.addItem("")
        self.LblOption = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblOption.setGeometry(QtCore.QRect(10, 235, 151, 16))
        self.LblOption.setObjectName("LblOption")
        self.CboOption = QtWidgets.QComboBox(hcmgis_font_convert_form)
        self.CboOption.setGeometry(QtCore.QRect(10, 251, 151, 21))
        self.CboOption.setObjectName("CboOption")
        self.CboOption.addItem("")
        self.CboOption.setItemText(0, "")
        self.CboOption.addItem("")
        self.CboOption.addItem("")
        self.CboOption.addItem("")
        self.CboOption.addItem("")
        self.BtnOKCancel = QtWidgets.QDialogButtonBox(hcmgis_font_convert_form)
        self.BtnOKCancel.setGeometry(QtCore.QRect(190, 339, 156, 31))
        self.BtnOKCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.BtnOKCancel.setObjectName("BtnOKCancel")
        self.LblInput = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblInput.setGeometry(QtCore.QRect(11, 9, 331, 16))
        self.LblInput.setObjectName("LblInput")
        self.BtnBrowseOutput = QtWidgets.QPushButton(hcmgis_font_convert_form)
        self.BtnBrowseOutput.setGeometry(QtCore.QRect(310, 300, 31, 21))
        self.BtnBrowseOutput.setObjectName("BtnBrowseOutput")
        self.LinOutput = QtWidgets.QLineEdit(hcmgis_font_convert_form)
        self.LinOutput.setGeometry(QtCore.QRect(10, 300, 291, 21))
        self.LinOutput.setObjectName("LinOutput")
        self.LblOutput = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblOutput.setGeometry(QtCore.QRect(10, 283, 291, 16))
        self.LblOutput.setObjectName("LblOutput")
        self.CboInput = QgsMapLayerComboBox(hcmgis_font_convert_form)
        self.CboInput.setGeometry(QtCore.QRect(10, 24, 331, 21))
        self.CboInput.setObjectName("CboInput")
        self.LblOutput_2 = QtWidgets.QLabel(hcmgis_font_convert_form)
        self.LblOutput_2.setGeometry(QtCore.QRect(10, 55, 331, 16))
        self.LblOutput_2.setObjectName("LblOutput_2")
        self.ListFields = QtWidgets.QListWidget(hcmgis_font_convert_form)
        self.ListFields.setGeometry(QtCore.QRect(10, 70, 331, 111))
        self.ListFields.setAlternatingRowColors(True)
        self.ListFields.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ListFields.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ListFields.setObjectName("ListFields")
        self.ChkSelectedFeaturesOnly = QtWidgets.QCheckBox(hcmgis_font_convert_form)
        self.ChkSelectedFeaturesOnly.setGeometry(QtCore.QRect(190, 253, 151, 17))
        self.ChkSelectedFeaturesOnly.setObjectName("ChkSelectedFeaturesOnly")

        self.retranslateUi(hcmgis_font_convert_form)
        self.BtnOKCancel.accepted.connect(hcmgis_font_convert_form.accept)
        self.BtnOKCancel.rejected.connect(hcmgis_font_convert_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_font_convert_form)

    def retranslateUi(self, hcmgis_font_convert_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_font_convert_form.setWindowTitle(_translate("hcmgis_font_convert_form", "Vietnamese Font Converter"))
        self.LblSourceFont.setText(_translate("hcmgis_font_convert_form", "Source Charset"))
        self.LblDestFont.setText(_translate("hcmgis_font_convert_form", "Target Charset"))
        self.CboSourceFont.setItemText(1, _translate("hcmgis_font_convert_form", "TCVN3"))
        self.CboSourceFont.setItemText(2, _translate("hcmgis_font_convert_form", "Unicode"))
        self.CboSourceFont.setItemText(3, _translate("hcmgis_font_convert_form", "VNI-Windows"))
        self.CboDestFont.setItemText(1, _translate("hcmgis_font_convert_form", "Unicode"))
        self.CboDestFont.setItemText(2, _translate("hcmgis_font_convert_form", "TCVN3"))
        self.CboDestFont.setItemText(3, _translate("hcmgis_font_convert_form", "VNI-Windows"))
        self.CboDestFont.setItemText(4, _translate("hcmgis_font_convert_form", "ANSI (Khong dau)"))
        self.LblOption.setText(_translate("hcmgis_font_convert_form", "Options"))
        self.CboOption.setItemText(1, _translate("hcmgis_font_convert_form", "UPPER CASE (IN HOA)"))
        self.CboOption.setItemText(2, _translate("hcmgis_font_convert_form", "lower case (in thường)"))
        self.CboOption.setItemText(3, _translate("hcmgis_font_convert_form", "Capitalize (Hoa đầu câu)"))
        self.CboOption.setItemText(4, _translate("hcmgis_font_convert_form", "Title (Hoa Mỗi từ)"))
        self.LblInput.setText(_translate("hcmgis_font_convert_form", "Input Layer"))
        self.BtnBrowseOutput.setText(_translate("hcmgis_font_convert_form", "..."))
        self.LblOutput.setText(_translate("hcmgis_font_convert_form", "Output Shapefile"))
        self.LblOutput_2.setText(_translate("hcmgis_font_convert_form", "Fields"))
        self.ChkSelectedFeaturesOnly.setText(_translate("hcmgis_font_convert_form", "Selected features only"))

from qgis.gui import QgsMapLayerComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_font_convert_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_font_convert_form()
    ui.setupUi(hcmgis_font_convert_form)
    hcmgis_font_convert_form.show()
    sys.exit(app.exec_())

