# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_customprojections_form.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_customprojections_form(object):
    def setupUi(self, hcmgis_customprojections_form):
        hcmgis_customprojections_form.setObjectName("hcmgis_customprojections_form")
        hcmgis_customprojections_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_customprojections_form.setEnabled(True)
        hcmgis_customprojections_form.resize(487, 362)
        hcmgis_customprojections_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_customprojections_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rad3do = QtWidgets.QRadioButton(hcmgis_customprojections_form)
        self.rad3do.setChecked(True)
        self.rad3do.setObjectName("rad3do")
        self.gridLayout_2.addWidget(self.rad3do, 0, 0, 1, 1)
        self.cboProvinces = QtWidgets.QComboBox(hcmgis_customprojections_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboProvinces.sizePolicy().hasHeightForWidth())
        self.cboProvinces.setSizePolicy(sizePolicy)
        self.cboProvinces.setObjectName("cboProvinces")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.cboProvinces.addItem("")
        self.gridLayout_2.addWidget(self.cboProvinces, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.radcustom = QtWidgets.QRadioButton(hcmgis_customprojections_form)
        self.radcustom.setObjectName("radcustom")
        self.verticalLayout.addWidget(self.radcustom)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.LblInput_2 = QtWidgets.QLabel(hcmgis_customprojections_form)
        self.LblInput_2.setObjectName("LblInput_2")
        self.gridLayout.addWidget(self.LblInput_2, 0, 0, 1, 1)
        self.LblInput_3 = QtWidgets.QLabel(hcmgis_customprojections_form)
        self.LblInput_3.setObjectName("LblInput_3")
        self.gridLayout.addWidget(self.LblInput_3, 0, 1, 1, 1)
        self.cboZone = QtWidgets.QComboBox(hcmgis_customprojections_form)
        self.cboZone.setObjectName("cboZone")
        self.cboZone.addItem("")
        self.cboZone.addItem("")
        self.gridLayout.addWidget(self.cboZone, 1, 0, 1, 1)
        self.cboKTT = QtWidgets.QComboBox(hcmgis_customprojections_form)
        self.cboKTT.setEditable(True)
        self.cboKTT.setObjectName("cboKTT")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.cboKTT.addItem("")
        self.gridLayout.addWidget(self.cboKTT, 1, 1, 1, 1)
        self.lbl_Format_2 = QtWidgets.QLabel(hcmgis_customprojections_form)
        self.lbl_Format_2.setObjectName("lbl_Format_2")
        self.gridLayout.addWidget(self.lbl_Format_2, 2, 0, 1, 2)
        self.cboParameters = QtWidgets.QComboBox(hcmgis_customprojections_form)
        self.cboParameters.setMaximumSize(QtCore.QSize(470, 16777215))
        self.cboParameters.setObjectName("cboParameters")
        self.cboParameters.addItem("")
        self.cboParameters.addItem("")
        self.gridLayout.addWidget(self.cboParameters, 3, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lbl_Format = QtWidgets.QLabel(hcmgis_customprojections_form)
        self.lbl_Format.setObjectName("lbl_Format")
        self.gridLayout_3.addWidget(self.lbl_Format, 0, 0, 1, 1)
        self.cboFormat = QtWidgets.QComboBox(hcmgis_customprojections_form)
        self.cboFormat.setObjectName("cboFormat")
        self.cboFormat.addItem("")
        self.cboFormat.addItem("")
        self.cboFormat.addItem("")
        self.cboFormat.addItem("")
        self.gridLayout_3.addWidget(self.cboFormat, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.LblInput_4 = QtWidgets.QLabel(hcmgis_customprojections_form)
        self.LblInput_4.setObjectName("LblInput_4")
        self.verticalLayout.addWidget(self.LblInput_4)
        self.txtProjections = QtWidgets.QTextEdit(hcmgis_customprojections_form)
        self.txtProjections.setObjectName("txtProjections")
        self.verticalLayout.addWidget(self.txtProjections)
        self.BtnOKCancel = QtWidgets.QDialogButtonBox(hcmgis_customprojections_form)
        self.BtnOKCancel.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.BtnOKCancel.setObjectName("BtnOKCancel")
        self.verticalLayout.addWidget(self.BtnOKCancel)

        self.retranslateUi(hcmgis_customprojections_form)
        self.BtnOKCancel.accepted.connect(hcmgis_customprojections_form.accept)
        self.BtnOKCancel.rejected.connect(hcmgis_customprojections_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_customprojections_form)

    def retranslateUi(self, hcmgis_customprojections_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_customprojections_form.setWindowTitle(_translate("hcmgis_customprojections_form", "VN-2000 Projections"))
        self.rad3do.setText(_translate("hcmgis_customprojections_form", "3 degree UTM zone for each Province in Vietnam"))
        self.cboProvinces.setCurrentText(_translate("hcmgis_customprojections_form", "Lai Châu"))
        self.cboProvinces.setItemText(0, _translate("hcmgis_customprojections_form", "Lai Châu"))
        self.cboProvinces.setItemText(1, _translate("hcmgis_customprojections_form", "Sơn La"))
        self.cboProvinces.setItemText(2, _translate("hcmgis_customprojections_form", "Kiên Giang"))
        self.cboProvinces.setItemText(3, _translate("hcmgis_customprojections_form", "Cà Mau"))
        self.cboProvinces.setItemText(4, _translate("hcmgis_customprojections_form", "Lào Cai"))
        self.cboProvinces.setItemText(5, _translate("hcmgis_customprojections_form", "Yên Bái"))
        self.cboProvinces.setItemText(6, _translate("hcmgis_customprojections_form", "Nghệ An"))
        self.cboProvinces.setItemText(7, _translate("hcmgis_customprojections_form", "Phú Thọ"))
        self.cboProvinces.setItemText(8, _translate("hcmgis_customprojections_form", "An Giang"))
        self.cboProvinces.setItemText(9, _translate("hcmgis_customprojections_form", "Thanh Hoá"))
        self.cboProvinces.setItemText(10, _translate("hcmgis_customprojections_form", "Vĩnh Phúc"))
        self.cboProvinces.setItemText(11, _translate("hcmgis_customprojections_form", "Hà Tây"))
        self.cboProvinces.setItemText(12, _translate("hcmgis_customprojections_form", "Đồng Tháp"))
        self.cboProvinces.setItemText(13, _translate("hcmgis_customprojections_form", "Cần Thơ"))
        self.cboProvinces.setItemText(14, _translate("hcmgis_customprojections_form", "Bạc Liêu"))
        self.cboProvinces.setItemText(15, _translate("hcmgis_customprojections_form", "Hà Nội"))
        self.cboProvinces.setItemText(16, _translate("hcmgis_customprojections_form", "Ninh Bình"))
        self.cboProvinces.setItemText(17, _translate("hcmgis_customprojections_form", "Hà Nam"))
        self.cboProvinces.setItemText(18, _translate("hcmgis_customprojections_form", "Hà Giang"))
        self.cboProvinces.setItemText(19, _translate("hcmgis_customprojections_form", "Hải Dương"))
        self.cboProvinces.setItemText(20, _translate("hcmgis_customprojections_form", "Hà Tĩnh"))
        self.cboProvinces.setItemText(21, _translate("hcmgis_customprojections_form", "Bắc Ninh"))
        self.cboProvinces.setItemText(22, _translate("hcmgis_customprojections_form", "Hưng Yên"))
        self.cboProvinces.setItemText(23, _translate("hcmgis_customprojections_form", "Thái Bình"))
        self.cboProvinces.setItemText(24, _translate("hcmgis_customprojections_form", "Nam Định"))
        self.cboProvinces.setItemText(25, _translate("hcmgis_customprojections_form", "Tây Ninh"))
        self.cboProvinces.setItemText(26, _translate("hcmgis_customprojections_form", "Vĩnh Long"))
        self.cboProvinces.setItemText(27, _translate("hcmgis_customprojections_form", "Sóc Trăng"))
        self.cboProvinces.setItemText(28, _translate("hcmgis_customprojections_form", "Trà Vinh"))
        self.cboProvinces.setItemText(29, _translate("hcmgis_customprojections_form", "Cao Bằng"))
        self.cboProvinces.setItemText(30, _translate("hcmgis_customprojections_form", "Long An"))
        self.cboProvinces.setItemText(31, _translate("hcmgis_customprojections_form", "Tiền Giang"))
        self.cboProvinces.setItemText(32, _translate("hcmgis_customprojections_form", "Bến Tre"))
        self.cboProvinces.setItemText(33, _translate("hcmgis_customprojections_form", "Hải Phòng"))
        self.cboProvinces.setItemText(34, _translate("hcmgis_customprojections_form", "TP.HCM"))
        self.cboProvinces.setItemText(35, _translate("hcmgis_customprojections_form", "Bình Dương"))
        self.cboProvinces.setItemText(36, _translate("hcmgis_customprojections_form", "Tuyên Quang"))
        self.cboProvinces.setItemText(37, _translate("hcmgis_customprojections_form", "Hoà Bình"))
        self.cboProvinces.setItemText(38, _translate("hcmgis_customprojections_form", "Quảng Bình"))
        self.cboProvinces.setItemText(39, _translate("hcmgis_customprojections_form", "Quảng Trị"))
        self.cboProvinces.setItemText(40, _translate("hcmgis_customprojections_form", "Bình Phước"))
        self.cboProvinces.setItemText(41, _translate("hcmgis_customprojections_form", "Bắc Kạn"))
        self.cboProvinces.setItemText(42, _translate("hcmgis_customprojections_form", "Thái Nguyên"))
        self.cboProvinces.setItemText(43, _translate("hcmgis_customprojections_form", "Bắc Giang"))
        self.cboProvinces.setItemText(44, _translate("hcmgis_customprojections_form", "Thừa Thiên - Huế"))
        self.cboProvinces.setItemText(45, _translate("hcmgis_customprojections_form", "Lạng Sơn"))
        self.cboProvinces.setItemText(46, _translate("hcmgis_customprojections_form", "Kon Tum"))
        self.cboProvinces.setItemText(47, _translate("hcmgis_customprojections_form", "Quảng Ninh"))
        self.cboProvinces.setItemText(48, _translate("hcmgis_customprojections_form", "Đồng Nai"))
        self.cboProvinces.setItemText(49, _translate("hcmgis_customprojections_form", "Bà Rịa - Vũng Tàu"))
        self.cboProvinces.setItemText(50, _translate("hcmgis_customprojections_form", "Quảng Nam"))
        self.cboProvinces.setItemText(51, _translate("hcmgis_customprojections_form", "Lâm Đồng"))
        self.cboProvinces.setItemText(52, _translate("hcmgis_customprojections_form", "Đà Nẵng"))
        self.cboProvinces.setItemText(53, _translate("hcmgis_customprojections_form", "Quảng Ngãi"))
        self.cboProvinces.setItemText(54, _translate("hcmgis_customprojections_form", "Ninh Thuận"))
        self.cboProvinces.setItemText(55, _translate("hcmgis_customprojections_form", "Khánh Hoà"))
        self.cboProvinces.setItemText(56, _translate("hcmgis_customprojections_form", "Bình Định"))
        self.cboProvinces.setItemText(57, _translate("hcmgis_customprojections_form", "Đắc Lắc"))
        self.cboProvinces.setItemText(58, _translate("hcmgis_customprojections_form", "Phú Yên"))
        self.cboProvinces.setItemText(59, _translate("hcmgis_customprojections_form", "Gia Lai"))
        self.cboProvinces.setItemText(60, _translate("hcmgis_customprojections_form", "Bình Thuận"))
        self.radcustom.setText(_translate("hcmgis_customprojections_form", "Create Custom Projections"))
        self.LblInput_2.setText(_translate("hcmgis_customprojections_form", "UTM Zone"))
        self.LblInput_3.setText(_translate("hcmgis_customprojections_form", "Central Meridian"))
        self.cboZone.setItemText(0, _translate("hcmgis_customprojections_form", "3 degree"))
        self.cboZone.setItemText(1, _translate("hcmgis_customprojections_form", "6 degree"))
        self.cboKTT.setItemText(0, _translate("hcmgis_customprojections_form", "102"))
        self.cboKTT.setItemText(1, _translate("hcmgis_customprojections_form", "103"))
        self.cboKTT.setItemText(2, _translate("hcmgis_customprojections_form", "104"))
        self.cboKTT.setItemText(3, _translate("hcmgis_customprojections_form", "104.5"))
        self.cboKTT.setItemText(4, _translate("hcmgis_customprojections_form", "104.75"))
        self.cboKTT.setItemText(5, _translate("hcmgis_customprojections_form", "105"))
        self.cboKTT.setItemText(6, _translate("hcmgis_customprojections_form", "105.5"))
        self.cboKTT.setItemText(7, _translate("hcmgis_customprojections_form", "105.75"))
        self.cboKTT.setItemText(8, _translate("hcmgis_customprojections_form", "106"))
        self.cboKTT.setItemText(9, _translate("hcmgis_customprojections_form", "106.25"))
        self.cboKTT.setItemText(10, _translate("hcmgis_customprojections_form", "106.5"))
        self.cboKTT.setItemText(11, _translate("hcmgis_customprojections_form", "107"))
        self.cboKTT.setItemText(12, _translate("hcmgis_customprojections_form", "107.25"))
        self.cboKTT.setItemText(13, _translate("hcmgis_customprojections_form", "107.5"))
        self.cboKTT.setItemText(14, _translate("hcmgis_customprojections_form", "107.75"))
        self.cboKTT.setItemText(15, _translate("hcmgis_customprojections_form", "108"))
        self.cboKTT.setItemText(16, _translate("hcmgis_customprojections_form", "108.25"))
        self.cboKTT.setItemText(17, _translate("hcmgis_customprojections_form", "108.5"))
        self.cboKTT.setItemText(18, _translate("hcmgis_customprojections_form", "111"))
        self.cboKTT.setItemText(19, _translate("hcmgis_customprojections_form", "114"))
        self.cboKTT.setItemText(20, _translate("hcmgis_customprojections_form", "117"))
        self.lbl_Format_2.setText(_translate("hcmgis_customprojections_form", "Choose parmater set to convert Datum VN-2000 <--> WGS84"))
        self.cboParameters.setItemText(0, _translate("hcmgis_customprojections_form", "-191.9044129,-39.30318279,-111.45032835,-0.00928836, 0.01975479, -0.004274, 0.252906278"))
        self.cboParameters.setItemText(1, _translate("hcmgis_customprojections_form", "-192.873,-39.382,-111.202,-0.00205,-0.0005,0.00335,0.0188"))
        self.lbl_Format.setText(_translate("hcmgis_customprojections_form", "Format"))
        self.cboFormat.setItemText(0, _translate("hcmgis_customprojections_form", "PROJ.4"))
        self.cboFormat.setItemText(1, _translate("hcmgis_customprojections_form", "ESRI WKT"))
        self.cboFormat.setItemText(2, _translate("hcmgis_customprojections_form", "PostGIS"))
        self.cboFormat.setItemText(3, _translate("hcmgis_customprojections_form", "GeoServer"))
        self.LblInput_4.setText(_translate("hcmgis_customprojections_form", "(Copy & paste PROJ.4 into QGIS Custom Projections)"))
        self.txtProjections.setHtml(_translate("hcmgis_customprojections_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_customprojections_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_customprojections_form()
    ui.setupUi(hcmgis_customprojections_form)
    hcmgis_customprojections_form.show()
    sys.exit(app.exec_())

