# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_global_microsoft_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_global_microsoft_form(object):
    def setupUi(self, hcmgis_global_microsoft_form):
        hcmgis_global_microsoft_form.setObjectName("hcmgis_global_microsoft_form")
        hcmgis_global_microsoft_form.setWindowModality(QtCore.Qt.NonModal)
        hcmgis_global_microsoft_form.setEnabled(True)
        hcmgis_global_microsoft_form.resize(972, 496)
        hcmgis_global_microsoft_form.setMouseTracking(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(hcmgis_global_microsoft_form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(hcmgis_global_microsoft_form)
        self.BtnApplyClose.setOrientation(QtCore.Qt.Horizontal)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.gridLayout_2.addWidget(self.BtnApplyClose, 10, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LblCountries = QtWidgets.QLabel(hcmgis_global_microsoft_form)
        self.LblCountries.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LblCountries.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblCountries.setObjectName("LblCountries")
        self.gridLayout.addWidget(self.LblCountries, 0, 0, 1, 2)
        self.TblCountries = QtWidgets.QTableWidget(hcmgis_global_microsoft_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TblCountries.sizePolicy().hasHeightForWidth())
        self.TblCountries.setSizePolicy(sizePolicy)
        self.TblCountries.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.TblCountries.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.TblCountries.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.TblCountries.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.TblCountries.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TblCountries.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TblCountries.setObjectName("TblCountries")
        self.TblCountries.setColumnCount(0)
        self.TblCountries.setRowCount(0)
        self.TblCountries.horizontalHeader().setCascadingSectionResizes(False)
        self.TblCountries.horizontalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.TblCountries, 4, 0, 1, 2)
        self.Filter = QgsFilterLineEdit(hcmgis_global_microsoft_form)
        self.Filter.setToolTip("")
        self.Filter.setShowClearButton(True)
        self.Filter.setShowSearchIcon(True)
        self.Filter.setShowSpinner(False)
        self.Filter.setProperty("qgisRelation", "")
        self.Filter.setObjectName("Filter")
        self.gridLayout.addWidget(self.Filter, 1, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 9, 0, 1, 2)

        self.retranslateUi(hcmgis_global_microsoft_form)
        self.BtnApplyClose.accepted.connect(hcmgis_global_microsoft_form.accept)
        self.BtnApplyClose.rejected.connect(hcmgis_global_microsoft_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_global_microsoft_form)

    def retranslateUi(self, hcmgis_global_microsoft_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_global_microsoft_form.setWindowTitle(_translate("hcmgis_global_microsoft_form", "Microsoft Global Building Footprints"))
        self.LblCountries.setText(_translate("hcmgis_global_microsoft_form", "Microsoft Global Building Footprints (Double click or Apply to download)"))
        self.TblCountries.setToolTip(_translate("hcmgis_global_microsoft_form", "Double Click to add selected Layers"))
        self.TblCountries.setSortingEnabled(True)
        self.Filter.setPlaceholderText(_translate("hcmgis_global_microsoft_form", "Search"))
from qgsfilterlineedit import QgsFilterLineEdit


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_global_microsoft_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_global_microsoft_form()
    ui.setupUi(hcmgis_global_microsoft_form)
    hcmgis_global_microsoft_form.show()
    sys.exit(app.exec_())
