# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_opendevelopmentmekong_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_opendevelopmentmekong_form(object):
    def setupUi(self, hcmgis_opendevelopmentmekong_form):
        hcmgis_opendevelopmentmekong_form.setObjectName("hcmgis_opendevelopmentmekong_form")
        hcmgis_opendevelopmentmekong_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_opendevelopmentmekong_form.setEnabled(True)
        hcmgis_opendevelopmentmekong_form.resize(577, 429)
        hcmgis_opendevelopmentmekong_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_opendevelopmentmekong_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.CboDataSource = QtWidgets.QComboBox(hcmgis_opendevelopmentmekong_form)
        self.CboDataSource.setMinimumSize(QtCore.QSize(131, 0))
        self.CboDataSource.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CboDataSource.setObjectName("CboDataSource")
        self.CboDataSource.addItem("")
        self.CboDataSource.addItem("")
        self.CboDataSource.addItem("")
        self.CboDataSource.addItem("")
        self.CboDataSource.addItem("")
        self.gridLayout.addWidget(self.CboDataSource, 0, 1, 1, 1)
        self.LblStatus = QtWidgets.QLabel(hcmgis_opendevelopmentmekong_form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout.addWidget(self.LblStatus, 2, 0, 1, 2)
        self.ChkAddtoMap = QtWidgets.QCheckBox(hcmgis_opendevelopmentmekong_form)
        self.ChkAddtoMap.setObjectName("ChkAddtoMap")
        self.gridLayout.addWidget(self.ChkAddtoMap, 6, 0, 1, 1)
        self.LblSourceLayers = QtWidgets.QLabel(hcmgis_opendevelopmentmekong_form)
        self.LblSourceLayers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.LblSourceLayers.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.LblSourceLayers.setObjectName("LblSourceLayers")
        self.gridLayout.addWidget(self.LblSourceLayers, 4, 0, 1, 2)
        self.LblDataSource = QtWidgets.QLabel(hcmgis_opendevelopmentmekong_form)
        self.LblDataSource.setObjectName("LblDataSource")
        self.gridLayout.addWidget(self.LblDataSource, 0, 0, 1, 1)
        self.LinOutputFolder = QtWidgets.QLineEdit(hcmgis_opendevelopmentmekong_form)
        self.LinOutputFolder.setEnabled(True)
        self.LinOutputFolder.setMouseTracking(True)
        self.LinOutputFolder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.LinOutputFolder.setAcceptDrops(False)
        self.LinOutputFolder.setText("")
        self.LinOutputFolder.setReadOnly(True)
        self.LinOutputFolder.setObjectName("LinOutputFolder")
        self.gridLayout.addWidget(self.LinOutputFolder, 7, 0, 1, 1)
        self.LsSourceLayers = QtWidgets.QListWidget(hcmgis_opendevelopmentmekong_form)
        self.LsSourceLayers.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.LsSourceLayers.setObjectName("LsSourceLayers")
        self.gridLayout.addWidget(self.LsSourceLayers, 5, 0, 1, 2)
        self.BtnOutputFolder = QtWidgets.QPushButton(hcmgis_opendevelopmentmekong_form)
        self.BtnOutputFolder.setEnabled(True)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.BtnOutputFolder.setFont(font)
        self.BtnOutputFolder.setObjectName("BtnOutputFolder")
        self.gridLayout.addWidget(self.BtnOutputFolder, 7, 1, 1, 1)
        self.ProgressBar = QtWidgets.QProgressBar(hcmgis_opendevelopmentmekong_form)
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout.addWidget(self.ProgressBar, 3, 0, 1, 2)
        self.LblFormat = QtWidgets.QLabel(hcmgis_opendevelopmentmekong_form)
        self.LblFormat.setObjectName("LblFormat")
        self.gridLayout.addWidget(self.LblFormat, 1, 0, 1, 1)
        self.CboFormat = QtWidgets.QComboBox(hcmgis_opendevelopmentmekong_form)
        self.CboFormat.setObjectName("CboFormat")
        self.CboFormat.addItem("")
        self.CboFormat.addItem("")
        self.CboFormat.addItem("")
        self.CboFormat.addItem("")
        self.CboFormat.addItem("")
        self.gridLayout.addWidget(self.CboFormat, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(hcmgis_opendevelopmentmekong_form)
        self.BtnApplyClose.setOrientation(QtCore.Qt.Horizontal)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_opendevelopmentmekong_form)
        self.BtnApplyClose.accepted.connect(hcmgis_opendevelopmentmekong_form.accept)
        self.BtnApplyClose.rejected.connect(hcmgis_opendevelopmentmekong_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_opendevelopmentmekong_form)

    def retranslateUi(self, hcmgis_opendevelopmentmekong_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_opendevelopmentmekong_form.setWindowTitle(_translate("hcmgis_opendevelopmentmekong_form", "OpenDevelopment Mekong DataHub"))
        self.CboDataSource.setItemText(0, _translate("hcmgis_opendevelopmentmekong_form", "ODMekong"))
        self.CboDataSource.setItemText(1, _translate("hcmgis_opendevelopmentmekong_form", "ODCambodia"))
        self.CboDataSource.setItemText(2, _translate("hcmgis_opendevelopmentmekong_form", "ODLao"))
        self.CboDataSource.setItemText(3, _translate("hcmgis_opendevelopmentmekong_form", "ODMyanmar"))
        self.CboDataSource.setItemText(4, _translate("hcmgis_opendevelopmentmekong_form", "ODVietnam"))
        self.ChkAddtoMap.setText(_translate("hcmgis_opendevelopmentmekong_form", "Add to Map"))
        self.LblSourceLayers.setText(_translate("hcmgis_opendevelopmentmekong_form", "Select layers"))
        self.LblDataSource.setText(_translate("hcmgis_opendevelopmentmekong_form", "Select Data Source"))
        self.BtnOutputFolder.setText(_translate("hcmgis_opendevelopmentmekong_form", "Browse...    "))
        self.LblFormat.setText(_translate("hcmgis_opendevelopmentmekong_form", "Format"))
        self.CboFormat.setItemText(0, _translate("hcmgis_opendevelopmentmekong_form", "JSON"))
        self.CboFormat.setItemText(1, _translate("hcmgis_opendevelopmentmekong_form", "SHAPE-ZIP"))
        self.CboFormat.setItemText(2, _translate("hcmgis_opendevelopmentmekong_form", "KML"))
        self.CboFormat.setItemText(3, _translate("hcmgis_opendevelopmentmekong_form", "GML2"))
        self.CboFormat.setItemText(4, _translate("hcmgis_opendevelopmentmekong_form", "GML3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_opendevelopmentmekong_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_opendevelopmentmekong_form()
    ui.setupUi(hcmgis_opendevelopmentmekong_form)
    hcmgis_opendevelopmentmekong_form.show()
    sys.exit(app.exec_())

