# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_split_field_form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_hcmgis_split_field_form(object):
    def setupUi(self, hcmgis_split_field_form):
        hcmgis_split_field_form.setObjectName("hcmgis_split_field_form")
        hcmgis_split_field_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_split_field_form.setEnabled(True)
        hcmgis_split_field_form.resize(536, 287)
        hcmgis_split_field_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_split_field_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.LblInput = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblInput.setObjectName("LblInput")
        self.verticalLayout.addWidget(self.LblInput)
        self.CboInput = QgsMapLayerComboBox(hcmgis_split_field_form)
        self.CboInput.setObjectName("CboInput")
        self.verticalLayout.addWidget(self.CboInput)
        self.LblOutput_2 = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblOutput_2.setObjectName("LblOutput_2")
        self.verticalLayout.addWidget(self.LblOutput_2)
        self.CboField = QgsFieldComboBox(hcmgis_split_field_form)
        self.CboField.setObjectName("CboField")
        self.verticalLayout.addWidget(self.CboField)
        self.LblChar = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblChar.setObjectName("LblChar")
        self.verticalLayout.addWidget(self.LblChar)
        self.CboChar = QtWidgets.QComboBox(hcmgis_split_field_form)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.CboChar.setFont(font)
        self.CboChar.setEditable(True)
        self.CboChar.setObjectName("CboChar")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.CboChar.addItem("")
        self.verticalLayout.addWidget(self.CboChar)
        self.ChkSelectedFeaturesOnly = QtWidgets.QCheckBox(hcmgis_split_field_form)
        self.ChkSelectedFeaturesOnly.setObjectName("ChkSelectedFeaturesOnly")
        self.verticalLayout.addWidget(self.ChkSelectedFeaturesOnly)
        self.LblStatus = QtWidgets.QLabel(hcmgis_split_field_form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.verticalLayout.addWidget(self.LblStatus)
        self.status = QtWidgets.QProgressBar(hcmgis_split_field_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(hcmgis_split_field_form)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_split_field_form)
        self.BtnApplyClose.accepted.connect(hcmgis_split_field_form.accept)
        self.BtnApplyClose.rejected.connect(hcmgis_split_field_form.reject)
        QtCore.QMetaObject.connectSlotsByName(hcmgis_split_field_form)

    def retranslateUi(self, hcmgis_split_field_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_split_field_form.setWindowTitle(_translate("hcmgis_split_field_form", "Split Fields"))
        self.LblInput.setText(_translate("hcmgis_split_field_form", "Input Layer"))
        self.LblOutput_2.setText(_translate("hcmgis_split_field_form", "Split field"))
        self.LblChar.setText(_translate("hcmgis_split_field_form", "Split character"))
        self.CboChar.setItemText(0, _translate("hcmgis_split_field_form", "Space"))
        self.CboChar.setItemText(1, _translate("hcmgis_split_field_form", "Tab"))
        self.CboChar.setItemText(2, _translate("hcmgis_split_field_form", ","))
        self.CboChar.setItemText(3, _translate("hcmgis_split_field_form", "_"))
        self.CboChar.setItemText(4, _translate("hcmgis_split_field_form", "-"))
        self.CboChar.setItemText(5, _translate("hcmgis_split_field_form", "/"))
        self.CboChar.setItemText(6, _translate("hcmgis_split_field_form", "|"))
        self.CboChar.setItemText(7, _translate("hcmgis_split_field_form", "\\"))
        self.CboChar.setItemText(8, _translate("hcmgis_split_field_form", "."))
        self.CboChar.setItemText(9, _translate("hcmgis_split_field_form", ":"))
        self.CboChar.setItemText(10, _translate("hcmgis_split_field_form", ";"))
        self.CboChar.setItemText(11, _translate("hcmgis_split_field_form", "~"))
        self.CboChar.setItemText(12, _translate("hcmgis_split_field_form", "`"))
        self.CboChar.setItemText(13, _translate("hcmgis_split_field_form", "!"))
        self.CboChar.setItemText(14, _translate("hcmgis_split_field_form", "@"))
        self.CboChar.setItemText(15, _translate("hcmgis_split_field_form", "#"))
        self.CboChar.setItemText(16, _translate("hcmgis_split_field_form", "$"))
        self.CboChar.setItemText(17, _translate("hcmgis_split_field_form", "%"))
        self.CboChar.setItemText(18, _translate("hcmgis_split_field_form", "&"))
        self.CboChar.setItemText(19, _translate("hcmgis_split_field_form", "*"))
        self.CboChar.setItemText(20, _translate("hcmgis_split_field_form", "("))
        self.CboChar.setItemText(21, _translate("hcmgis_split_field_form", ")"))
        self.CboChar.setItemText(22, _translate("hcmgis_split_field_form", "{"))
        self.CboChar.setItemText(23, _translate("hcmgis_split_field_form", "}"))
        self.CboChar.setItemText(24, _translate("hcmgis_split_field_form", "["))
        self.CboChar.setItemText(25, _translate("hcmgis_split_field_form", "]"))
        self.CboChar.setItemText(26, _translate("hcmgis_split_field_form", "\'"))
        self.CboChar.setItemText(27, _translate("hcmgis_split_field_form", "\""))
        self.CboChar.setItemText(28, _translate("hcmgis_split_field_form", "<"))
        self.CboChar.setItemText(29, _translate("hcmgis_split_field_form", ">"))
        self.ChkSelectedFeaturesOnly.setText(_translate("hcmgis_split_field_form", "Selected features only"))

from qgsfieldcombobox import QgsFieldComboBox
from qgsmaplayercombobox import QgsMapLayerComboBox

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_split_field_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_split_field_form()
    ui.setupUi(hcmgis_split_field_form)
    hcmgis_split_field_form.show()
    sys.exit(app.exec_())

