# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hcmgis_wof_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hcmgis_wof_form(object):
    def setupUi(self, hcmgis_wof_form):
        hcmgis_wof_form.setObjectName("hcmgis_wof_form")
        hcmgis_wof_form.setWindowModality(QtCore.Qt.ApplicationModal)
        hcmgis_wof_form.setEnabled(True)
        hcmgis_wof_form.resize(426, 273)
        hcmgis_wof_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(hcmgis_wof_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(hcmgis_wof_form)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(hcmgis_wof_form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.cboCountry = QtWidgets.QComboBox(hcmgis_wof_form)
        self.cboCountry.setObjectName("cboCountry")
        self.gridLayout.addWidget(self.cboCountry, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(hcmgis_wof_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LinOutputFolder = QtWidgets.QLineEdit(hcmgis_wof_form)
        self.LinOutputFolder.setReadOnly(True)
        self.LinOutputFolder.setObjectName("LinOutputFolder")
        self.gridLayout_2.addWidget(self.LinOutputFolder, 1, 0, 1, 1)
        self.Label = QtWidgets.QLabel(hcmgis_wof_form)
        self.Label.setObjectName("Label")
        self.gridLayout_2.addWidget(self.Label, 0, 0, 1, 2)
        self.BtnOutputFolder = QtWidgets.QPushButton(hcmgis_wof_form)
        self.BtnOutputFolder.setObjectName("BtnOutputFolder")
        self.gridLayout_2.addWidget(self.BtnOutputFolder, 1, 1, 1, 1)
        self.LblStatus = QtWidgets.QLabel(hcmgis_wof_form)
        self.LblStatus.setText("")
        self.LblStatus.setObjectName("LblStatus")
        self.gridLayout_2.addWidget(self.LblStatus, 2, 0, 1, 2)
        self.status = QtWidgets.QProgressBar(hcmgis_wof_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.gridLayout_2.addWidget(self.status, 3, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.BtnApplyClose = QtWidgets.QDialogButtonBox(hcmgis_wof_form)
        self.BtnApplyClose.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Close)
        self.BtnApplyClose.setObjectName("BtnApplyClose")
        self.verticalLayout.addWidget(self.BtnApplyClose)

        self.retranslateUi(hcmgis_wof_form)
        self.BtnApplyClose.accepted.connect(hcmgis_wof_form.accept) # type: ignore
        self.BtnApplyClose.rejected.connect(hcmgis_wof_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(hcmgis_wof_form)

    def retranslateUi(self, hcmgis_wof_form):
        _translate = QtCore.QCoreApplication.translate
        hcmgis_wof_form.setWindowTitle(_translate("hcmgis_wof_form", "Download WOF Data by Country"))
        self.label.setText(_translate("hcmgis_wof_form", "Download Global Administrative Areas by Country from Who\'s On First (WOF)"))
        self.label_2.setText(_translate("hcmgis_wof_form", "All available placetype admin levels will be included with polygons and points"))
        self.label_3.setText(_translate("hcmgis_wof_form", "Select Country"))
        self.Label.setText(_translate("hcmgis_wof_form", "Select folder to save shapefile(s):"))
        self.BtnOutputFolder.setText(_translate("hcmgis_wof_form", "Browse..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hcmgis_wof_form = QtWidgets.QDialog()
    ui = Ui_hcmgis_wof_form()
    ui.setupUi(hcmgis_wof_form)
    hcmgis_wof_form.show()
    sys.exit(app.exec_())
